# Generated by Django 3.2.5 on 2021-07-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=20, unique=True)),
                ('int_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('last_cost', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('p', 'Producto'), ('s', 'Servicio'), ('o', 'Otro')], default='p', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('saleable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
            options={
                'ordering': ('int_code',),
            },
        ),
    ]
